### ISSUE TITLE
is there MAUI support planned?

### ISSUE THREAD

**Issue by gsgou** [crowdin/xamarin-sdk#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrii-bodnar** [comment]
@gsgou it's not supported.

There was an attempt to add MAUI support - https://github.com/crowdin/xamarin-sdk/pull/5

Maybe, @bnoffer can shed some light on this.

Anyway, you can always utilize the Crowdin CDN endpoints described here - https://support.crowdin.com/content-delivery/#for-web-applications
